sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8 
#before_install:
#  - cat /etc/hosts # optionally check the content *before*
#  - sudo hostname "$(hostname | cut -c1-63)"
#  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
#  - sudo mv /tmp/hosts /etc/hosts
#  - cat /etc/hosts # optionally check the content *after*
addons:
  hosts:
    - myshorthost
  hostname: myshorthost

script: ant -buildfile ./framework/build.xml test

after_failure:
    find samples-and-tests -name '*.failed.html' -exec echo {} \; -exec cat {} \;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6da3b55e59cded84b8bd
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: always
